"""empty message

Revision ID: 485d9d8a5dd7
Revises: fc31a145be19
Create Date: 2025-09-27 11:59:50.057459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485d9d8a5dd7'
down_revision = 'fc31a145be19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    op.drop_table('user')
    # ### end Alembic commands ###
